#!/bin/sh

# startx with custom xinit if EVER needed
#alias startx="startx $XINITRC"

# put sudo in front of some commands
for command in mount umount pacman su shutdown poweroff reboot ; do
    alias $command="sudo $command"
done; unset command

# tell electron to use wayland
alias discord="discord --ozone-platform-hint=auto --enable-features=WaylandWindowDecorations"
alias codium="codium --ozone-platform-hint=auto --enable-features=WaylandWindowDecorations"
alias obsidian="obsidian --ozone-platform-hint=auto --enable-features=WaylandWindowDecorations"

# verbose and other settings
alias \
    cp="cp -iv" \
    mv="mv -iv" \
    rm="rm -vI" \
    bc="bc -ql" \
    mkdir="mkdir -pv" \
    ffmpeg="ffmpeg -hide_banner"

# colors
alias \
    ls="ls -hN --color=auto --group-directories-first" \
    grep="grep --color=auto" \
    diff="diff --color=auto" \
    ccat="highlight --out-format=ansi" \
    ip="ip -color=auto"

# abbreviations
alias \
    cd.="cd .." \
    cd..="cd ../.." \
    ll="ls -l" \
    la="ls -la" \
    update="pacman -Sy archlinux-keyring && pacman -Su" \
    vim="nvim" \
    lf="lfub" \
    fgrep="find . | grep"

# actual aliases
alias \
    webcam="qv4l2" \
    sizeof="du -sh"

alias gemma4="llama-server -hf unsloth/gemma-4-12b-it-GGUF:UD-Q4_K_XL"
alias gemma4img="llama-server -hf unsloth/gemma-4-12b-it-GGUF:UD-Q4_K_XL --image-min-tokens 1120 --image-max-tokens 1120 --ubatch-size 2048 --batch-size 2048"
