#!/bin/sh

# put sudo in front of some commands
for command in mount umount pacman su shutdown poweroff reboot ; do
    alias $command="sudo $command"
done; unset command

# tell electron to use wayland
alias discord="discord --ozone-platform-hint=auto --enable-features=WaylandWindowDecorations"
alias codium="codium --ozone-platform-hint=auto --enable-features=WaylandWindowDecorations"
alias obsidian="obsidian --ozone-platform-hint=auto --enable-features=WaylandWindowDecorations"

# verbose and other settings
alias \
    cp="cp -iv" \
    mv="mv -iv" \
    rm="rm -vI" \
    bc="bc -ql" \
    mkdir="mkdir -pv" \
    yt="yt-dlp --add-metadata --ignore-errors --windows-filenames --output \"%(title)s.%(ext)s\"" \
    yta="yt -f \"bestaudio[ext=m4a]\" --embed-thumbnail" \
    ffmpeg="ffmpeg -hide_banner"

# colors
alias \
    ls="ls -hN --color=auto --group-directories-first" \
    grep="grep --color=auto" \
    diff="diff --color=auto" \
    ccat="highlight --out-format=ansi" \
    ip="ip -color=auto"

# abbreviations
alias \
    cd.="cd .." \
    cd..="cd ../.." \
    ll="ls -l" \
    la="ls -la" \
    update="pacman -Sy archlinux-keyring && pacman -Su" \
    vim="nvim" \
    lf="lfub" \
    ncmpcpp="ncmpcpp-ueberzug" \
    fgrep="find . | grep"

# actual aliases
alias \
    webcam="qv4l2" \
    sizeof="du -sh"
