#!/bin/sh
# Executed by startx (run your window manager from here)

# run xprofile
if [ -f "$XDG_CONFIG_HOME/x11/xprofile" ]; then
    . "$XDG_CONFIG_HOME/x11/xprofile"
else
    . "$HOME/.xprofile"
fi

# run wm
exec i3 --shmlog-size 0
