# for i3status-rust

[theme]
theme = "modern"
[theme.overrides]
idle_bg = "#111111"
idle_fg = "#dedede"
info_bg = "#3b4837"
info_fg = "#a7c99d"

[icons]
icons = "awesome6"

#[[block]]
#block = "focused_window"

[[block]]
block = "music"
format = " $icon {$combo.str(max_w:25, rot_interval:0.75) $play |} "
# player = "mpd"

[[block]]
block = "cpu"
interval = 1

[[block]]
block = "memory"
format = " $icon  $mem_used_percents.eng(w:1) "

[[block]]
block = "sound"

[[block]]
block = "time"
interval = 5
format = " $icon $timestamp.datetime(f:'%a %m-%d %R')"
[[block.click]]
button = "left"
cmd = "rofi-calendar"

# [[block]]
# block = "battery"
# if_command = "test -e /sys/class/power_supply/BAT0"

